### ISSUE TITLE
Layout Footer

### ISSUE THREAD

**Issue by pavelracu** [almeiduh/vejo-em-casa-wp#1]
Done.
![image](https://user-images.githubusercontent.com/18737263/78610846-9f696e80-785d-11ea-9205-94c1c860324b.png)

**Comment by almeiduh** [comment]
This color is still not ok 
![image](https://user-images.githubusercontent.com/6568760/78650202-7f19ce00-78b6-11ea-9c9f-9b97d64c5c9a.png)
